#index:
#    path: /
#    defaults: { _controller: 'App\Controller\DefaultController::index' }

register:
    path: /register
    controller: 'App\Controller\RegisterProductController::register'
    methods: ['POST']
